[project]
name = "lensure"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "atproto>=0.0.65",
    "cryptography>=46.0.7",
    "diffusers>=0.37.1",
    "flake8>=7.3.0",
    "imagehash>=4.3.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "polars>=1.40.1",
    "python-dotenv>=1.2.2",
    "pywavelets>=1.9.0",
    "reedsolo>=1.7.0",
    "requests>=2.33.1",
    "safetensors>=0.7.0",
    "scikit-image>=0.26.0",
    "tk>=0.1.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.67.3",
    "transformers>=5.7.0",
    "typer>=0.24.1",
]

[project.scripts]
lensure = "lensure.cli:app"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pytest>=9.0.3",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
